=== QuackProfit/RatOS-configuration/boards/board-definition.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://os.ratrig.com/board-defintion.schema.json",
	"title": "Control Board",
	"description": "A 3d printer control board",
	"type": "object",
	"properties": {
	  "serialPath": {
		"description": "The path for serial communication with this MCU",
		"type": "string"
	  },
	  "name": {
		"description": "The name of the control board",
		"type": "string"
	  },
	  "manufacturer": {
		  "description": "The name of the manufacturer of this board",
		  "type": "string"
	  },
	  "firmwareBinaryName": {
		  "description": "The firmware binary filename",
		  "type": "string"
	  },
	  "compileScript": {
		  "description": "The path to the compilation script if the board supports automatic firmware compilation, relative to the board definition directory",
		  "type": "string"
	  },
	  "flashScript": {
		"description": "The path to the flashing script if the board supports automatic firmware flashing, relative to the board definition directory",
		"type": "string"
	  },
	  "flashInstructions": {
		"description": "Instructions for how to make sure the board can be automatically flashed",
		"type": "string"
	  }
	},
	"required": [ "serialPath", "name", "manufacturer", "firmwareBinaryName" ]
  }

=== QuackProfit/RatOS-configuration/boards/btt-octopus-pro-446/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Octopus Pro 446",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-octopus-pro-446",
	"firmwareBinaryName": "firmware-btt-octopus-pro-446.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "Flashing only works if the SD card slot on the Octopus Pro is empty."
}
